spring:
  application:
    name: motorplus
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/motorplus}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:Admin1234}
    driver-class-name: org.postgresql.Driver

mybatis:
  type-handlers-package: com.motorplus.motorplus.mybatis
  default-scripting-language: org.apache.ibatis.scripting.xmltags.XMLLanguageDriver
  configuration:
    map-underscore-to-camel-case: true

